// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLeSzwPpiiVDaQ2Y__uTtvOdGUxoUXlwU',
    appId: '1:246210817329:web:ffaec9dd90a4cb9a4d5410',
    messagingSenderId: '246210817329',
    projectId: 'chatiyaao',
    authDomain: 'chatiyaao.firebaseapp.com',
    storageBucket: 'chatiyaao.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7rYLWNb6d6ef79XpWYmDm4Svu9q7ZBOk',
    appId: '1:246210817329:android:e260fc34c9086a3f4d5410',
    messagingSenderId: '246210817329',
    projectId: 'chatiyaao',
    storageBucket: 'chatiyaao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWK7QGVp5AgTTixOQZtT9I7rTwFrro0bE',
    appId: '1:246210817329:ios:087d446aa84fc6c24d5410',
    messagingSenderId: '246210817329',
    projectId: 'chatiyaao',
    storageBucket: 'chatiyaao.appspot.com',
    androidClientId: '246210817329-bk7e5h9t6bgi37a6bt72218mdfeprgtt.apps.googleusercontent.com',
    iosClientId: '246210817329-7skmv4skdqbkfvfjn9s4p6li5830co50.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWK7QGVp5AgTTixOQZtT9I7rTwFrro0bE',
    appId: '1:246210817329:ios:087d446aa84fc6c24d5410',
    messagingSenderId: '246210817329',
    projectId: 'chatiyaao',
    storageBucket: 'chatiyaao.appspot.com',
    androidClientId: '246210817329-bk7e5h9t6bgi37a6bt72218mdfeprgtt.apps.googleusercontent.com',
    iosClientId: '246210817329-7skmv4skdqbkfvfjn9s4p6li5830co50.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
